### ISSUE TITLE
Minor spelling/grammar suggestions.

### ISSUE THREAD

**Issue by ChrisKeefe** [dereksonderegger/570#7]
Hi Derek!
I got a lot of value out of this text when I took 570 a couple years ago, and would be happy to contribute spelling/grammar checks to the text if they're welcome. 

What are your preferences re: proposing contributions. Should I just fork and open a pull request or two?
Best,
Chris

**Comment by dereksonderegger** [comment]
Hi Chris,  

Forking and then a pull request is perfect for me.  That would be really helpful!
